### PR TITLE
#1514 Modify governor model

### PR DESCRIPTION
**Pull request by adriguir**

### CODE REVIEW

**Comment by adriguir** [comment]
@gautierbureau @rosiereflo it seems there is a problem with the pipeline related to the IIDM library in a way or another.

**Review by MarianneSaugierRTE — APPROVED** [review]

**Comment by gautierbureau** [comment]
> @gautierbureau @rosiereflo it seems there is a problem with the pipeline related to the IIDM library in a way or another.

Issue is on sundials but it is dealt with

**Review by cossartque — APPROVED** [review]

**Comment by cossartque** [comment]
Should we merge now ?

**Comment by MarianneSaugierRTE** [comment]
> Should we merge now ?

Yes!

**Pull request merged**
