### PR TITLE
#2293 use adept 2.1.1

### LINKED ISSUE #2293: Use Adept 2.1.1

### PR DESCRIPTION
**Pull request by rosiereflo**
closes #2293

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (new model, new feature and bug fix)
- [x] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

### CODE REVIEW

**Comment by adriguir** [comment]
Any reason not to review it and go ahead?

**Comment by rosiereflo** [comment]
> Any reason not to review it and go ahead?

I just need to make sure this compiles on Windows, and until now the nightly was not working. I should be able to go on now

**Comment by rosiereflo** [comment]
OK on Windows, ready to merge!

**Comment by gautierbureau** [comment]
Can you squash the commits ? thanks

**Comment by rosiereflo** [comment]
> Can you squash the commits ? thanks

done

**Review by gautierbureau — APPROVED** [review]

**Pull request merged**
