### PR TITLE
#1249 Update Adept version

### LINKED ISSUE #1249: Use adept 2.0.8 release
A new release is available since late August 2020: it would be nice to use it into Dynawo.
In addition, performances guidelines (such as using the fast exponential evaluation) should be tried to see if they bring any benefit or not in our case.

### PR DESCRIPTION
**Pull request by lecourtoisflo**
closes #1249

### CODE REVIEW

**Comment by lecourtoisflo** [comment]
Validated on linux but not on windows

**Comment by rosiereflo** [comment]
Did you try to play with the new options as suggested in the ticket?

**Comment by adriguir** [comment]
> Did you try to play with the new options as suggested in the ticket?

To be honest, I don't know if there are new options with the new version but I don't know if we had already tested them previously.

**Comment by rosiereflo** [comment]
> > Did you try to play with the new options as suggested in the ticket?
> 
> To be honest, I don't know if there are new options with the new version but I don't know if we had already tested them previously.

yes, I saw that it was already there before but we can take a quick look :) (I think I took a look once and found nothing interesting, but costs nothing to try again with latest version)

**Comment by lecourtoisflo** [comment]
> > > Did you try to play with the new options as suggested in the ticket?
> > 
> > 
> > To be honest, I don't know if there are new options with the new version but I don't know if we had already tested them previously.
> 
> yes, I saw that it was already there before but we can take a quick look :) (I think I took a look once and found nothing interesting, but costs nothing to try again with latest version)

I'll try

**Comment by lecourtoisflo** [comment]
option to add FAST EXPONENTIAL did not improve performances (in some cases, it even worsen them)
adding march=native in case of gcc, as indicatyed in Adept documentation, improves performances by 1 second

**Comment by adriguir** [comment]
1 second for which test case?

**Comment by lecourtoisflo** [comment]
> 1 second for which test case?

on big test cases

**Comment by lecourtoisflo** [comment]
Compiles on Windows

**Review by rosiereflo — APPROVED** [review]

**Review by gautierbureau — APPROVED** [review]

**Pull request merged**
