### PR TITLE
#1407 Add the possibility to specify a set of xsl ids to apply instea…

### PR DESCRIPTION
**Pull request by rosiereflo**
…d of applying everything

### CODE REVIEW

**Review by gautierbureau — APPROVED** [review]
Could you had an example of the use of the option in the README in the folder ?

**Comment by rosiereflo** [comment]
> Could you had an example of the use of the option in the README in the folder ?

sure let me add this

**Comment by rosiereflo** [comment]
After taking a look at our README and the possibilities of this script I would propose to not mention it before it can be used easily (today the user has to specify one by one the xsl he wants to apply and thus needs to have the knowledge of which xsl should be used). IMHO we should advertise this when we have a clean command to update from version x1.y1.z1 to version x2.y2.z2.

**Comment by rosiereflo** [comment]
following my previous comment I have added a description only in the xsl folder

**Review by gautierbureau — APPROVED** [review]

**Pull request merged**
