### PR TITLE
1807 detect lost equipments node breaker

### LINKED ISSUE #1807: [API - Lost equipments] Properly detect disconnection of components in case of NODE_BREAKER voltage level
When a component (generator, load...) is connected to a NODE_BREAKER voltage level, we detect the disconnection of the switch connected to the component but not the disconnection of the component itself.

Input iidm:
```
 <voltageLevel id="MYVL"  topologyKind="NODE_BREAKER">
      <nodeBreakerTopology nodeCount="...">
        <switch id="MySwitch" name="MySwitch" kind="BREAKER" retained="true" open="false" node1="0" node2="1"/>
  ....
  <load id="MyLoad" node="1"/>

```
output iidm:
```
 <voltageLevel id="MYVL"  topologyKind="NODE_BREAKER">
      <nodeBreakerTopology nodeCount="...">
        <switch id="MySwitch" name="MySwitch" kind="BREAKER" retained="true" open="true" node1="0" node2="1"/>
  ....
  <load id="MyLoad" node="1"/>
```

gives the following lost equipment file:
```
<lostEquipments xmlns="http://www.rte-france.com/dynawo">
  <lostEquipment id="MySwitch" type="SWITCH"/>
</lostEquipments>

```
whereas we would like to have:
```
<lostEquipments xmlns="http://www.rte-france.com/dynawo">
  <lostEquipment id="MySwitch" type="SWITCH"/>
  <lostEquipment id="MyLoad" type="LOAD"/>
</lostEquipments>
```

### PR DESCRIPTION
**Pull request by valleefred**
Closes #1807

### CODE REVIEW

**Comment by gautierbureau** [comment]
You have a conflict could you rebase ?

**Comment by valleefred** [comment]
> You have a conflict could you rebase ?

Rebase done !

**Comment by valleefred** [comment]
Beware of #1828 while merging !

**Review by gautierbureau — APPROVED** [review]

**Comment by gautierbureau** [comment]
> Beware of #1828 while merging !

I merged it and now there is a new conflict !

**Comment by valleefred** [comment]
> > Beware of #1828 while merging !
> 
> I merged it and now there is a new conflict !

Normal, I've just resolved this conflict too.

**Pull request merged**
