### PR TITLE
#874 fix extvar file generation + switchOff signals connection for load, tfo and tapChanger

### PR DESCRIPTION
**Pull request by MarianneSaugierRTE**

### CODE REVIEW

**Comment by rosiereflo** [comment]
Woups sorry I think I did something wrong. I pushed a commit on the branch with a fix for the sonar issues but it seems that it erased this MR. @MarianneSaugierRTE could you please reupload it with the small modification I added? Thanks and sorry

**Comment by MarianneSaugierRTE** [comment]
No pb! We'll see if I did well ;)

**Comment by MarianneSaugierRTE** [comment]
I updated the references for this PR

**Comment by MarianneSaugierRTE** [comment]
@rosiereflo I rebased and updated the references. Sonar is not happy, but I remember you made some corrections to fix it. Is this something else or did I miss something in the rebase?

**Comment by rosiereflo** [comment]
You can bypass SonarCloud decision (based on existing duplication)

**Comment by rosiereflo** [comment]
Do you want me to merge this?

**Comment by MarianneSaugierRTE** [comment]
yes!

**Pull request merged**
