### PR TITLE
1089 running propagation

### PR DESCRIPTION
**Pull request by MarianneSaugierRTE**
@cossartque Can you review the models part?
* modelica models doesn't extend a switchOff model anymore, they only have a boolean running
* the switchOff model is now a unitDynamicModel inside the preassembled models
* inside the preassembled models, the swhitchOff model running variable is connected to the different unitDynamicModels running variables
* for injections, non running equations are: terminal.i=Complex(0);
* for branches, non running equations are: terminal1.i=Complex(0) and terminal1.V=terminal2.V. This is not perfect but is a satisfactory temporary solution (better than what we had). 

@gautierbureau Can you have a look to the xsl files? I might have a problem with namespace...

### CODE REVIEW

**Comment by MarianneSaugierRTE** [comment]
@cossartque Can you also check full OM test cases? I updated them but my OM is too old and some of the tests don't work for me. Thanks!

**Comment by rosiereflo** [comment]
Does this stabilize the generator disconnection event?

**Comment by MarianneSaugierRTE** [comment]
> Does this stabilize the generator disconnection event?

Yes

**Review by cossartque — COMMENTED** [review]
The .mo files seem fine to me !
However, for the full OM tests, I have the following issues (that might come from before this PR as they are not linked to the switchoff).
For the SMIBStepPm, I have an error "Illegal access of protected element lambdafPu".
For the HVDC test case and the associated HvdcVSCNoBlockingFunction.mo model in the BaseModel directory, I have an error "Illegal access of protected element PInjPu".
I think these full OM test cases have not been updated when some variables became protected in the InjectorIDQ.mo and Machines/BaseClasses.mo models. Maybe you can put these variables as public ?

**Comment by MarianneSaugierRTE** [comment]
> r the SMIBStepPm, I have an error "Illegal access of protected element la

Thanks for checking. I have open a new issue for this problem #1104 , as it is not related to the switchOff issue as you said. What is weird is that, for example for lambdafPu in the machine model, it has always been a protected value... same for other flux variables...

**Review by cossartque — APPROVED** [review]
OK. I have no other issue then.

**Review by rosiereflo — APPROVED** [review]

**Pull request closed without merging**
