### PR TITLE
#3438 [Windows] Use Ninja as the CMake Generator

### PR DESCRIPTION
**Pull request by barondim**
**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [x] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

### CODE REVIEW

**Comment by barondim** [comment]
OpenModelica compilation can fail on the first try

**Comment by gautierbureau** [comment]
> OpenModelica compilation may fail on the first attempt. The user might need to re-run the 3rdParty compilation to complete it successfully

I don't like this

**Comment by barondim** [comment]
- [ ] Do not merge

**Comment by barondim** [comment]
> > OpenModelica compilation may fail on the first attempt. The user might need to re-run the 3rdParty compilation to complete it successfully
> 
> I don't like this

This problem is solved now

**Review by gautierbureau — APPROVED** [review]

**Pull request merged**
