### PR TITLE
#1279 Add a new _INIT model for the recaculation of the limits of the restorative load

### PR DESCRIPTION
**Pull request by cossartque**

### CODE REVIEW

**Review by marcochiaramello — APPROVED** [review]

**Comment by adriguir** [comment]
I don't really know how we should proceed in terms of library management. In your development, you created a specific INIT model and a specific preassembled model. There are at least two other ways of doing it:
- make this the default init model
- make this the default init model but having a parameter to decide if we want to apply this or not.

@MarianneSaugierRTE do you have an advice on this?
If I remember right, we had the same kind of problems with governors for DynaWaltz but the init model enforcing the limits is on the private repo so really tagged as specific for RTE....

**Comment by MarianneSaugierRTE** [comment]
> I don't really know how we should proceed in terms of library management. In your development, you created a specific INIT model and a specific preassembled model. There are at least two other ways of doing it:
> 
>     * make this the default init model
> 
>     * make this the default init model but having a parameter to decide if we want to apply this or not.
> 
> 
> @MarianneSaugierRTE do you have an advice on this?
> If I remember right, we had the same kind of problems with governors for DynaWaltz but the init model enforcing the limits is on the private repo so really tagged as specific for RTE....

Indeed we did a similar thing with the voltage regulator limits, in order to have closer results with the current operational tool. We put the model in the private repo, and this is the one we use by default in all simulations on large scale systems. If you need this model for the same reason, getting closer results with the current operational tool, I would suggest a similar solution.

**Comment by adriguir** [comment]
The point here is that we would like to have it public to show results on some publicly available test cases. Well I believe we can leave it as in the development at the moment.

**Comment by cossartque** [comment]
I think having it in the public repo makes it easier to use it in DFL and PowSyBl no ?

**Comment by MarianneSaugierRTE** [comment]
> int here is that we would like to have it pu

No pb!

**Review by adriguir — APPROVED** [review]

**Pull request merged**
