### PR TITLE
#2428 fix transcription of state variables for evalFAdept

### LINKED ISSUE #2428: [Model compilation] some state variables are not properly converted into adept variables

### PR DESCRIPTION
**Pull request by rosiereflo**
closes #2428

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

### CODE REVIEW

**Comment by ErwanGuichard49** [comment]
With this branch, the compilation of dynawo-rte (with the SecondOrder from MSL instead of the one from Dynawo) succeeds for all but four preassembled : GeneratorSynchronousFourWindingsGoverDk6GtVRDk6, GeneratorSynchronousFourWindingsGoverDk6GtVRDk6Tfo, GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlst, GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlstTfo.

The models causing these failures are GoverDk6Gt and VRAlst. In GoverDk6Gt, the SecondOrder filter is connected to a FixedDelay block. In VRAlst, the SecondOrder filter is connected to a CombiTable1Ds block.

**Comment by ErwanGuichard49** [comment]
The compilation logs :

[GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlst.log](https://github.com/dynawo/dynawo/files/9141199/GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlst.log)
[GeneratorSynchronousFourWindingsGoverDk6GtVRDk6.log](https://github.com/dynawo/dynawo/files/9141216/GeneratorSynchronousFourWindingsGoverDk6GtVRDk6.log)

**Comment by ErwanGuichard49** [comment]
I have just pushed 515_restore_MSL_SecondOrder on GitLab.

**Comment by ErwanGuichard49** [comment]
Actually, the nrt passed with the SecondOrder from Dynawo, but the goal of this issue is to allow for an efficient simulation with the SecondOrder from Modelica Standard Library. Hence the branch 515.

**Comment by rosiereflo** [comment]
I wasn't able to reproduce the compilation error locally

**Comment by rosiereflo** [comment]
Looks ok on my side now

**Review by adriguir — APPROVED** [review]

**Pull request merged**
