### PR TITLE
#1714 Remove useless boost dependency.

### PR DESCRIPTION
**Pull request by gautierbureau**

### CODE REVIEW

**Review by rosiereflo — APPROVED** [review]

**Comment by rosiereflo** [comment]
Did you test the compilation of private projects?

**Comment by gautierbureau** [comment]
> Did you test the compilation of private projects?

The private projects don't need this library as only powsybl-iidm and now that we don't build tests for powsybl-iidm nobody needs it.

**Comment by rosiereflo** [comment]
> > Did you test the compilation of private projects?
> 
> The private projects don't need this library as only powsybl-iidm and now that we don't build tests for powsybl-iidm nobody needs it.

ok, but did you test it to be sure?

**Comment by gautierbureau** [comment]
> > > Did you test the compilation of private projects?
> > 
> > 
> > The private projects don't need this library as only powsybl-iidm and now that we don't build tests for powsybl-iidm nobody needs it.
> 
> ok, but did you test it to be sure?

it is ok

**Pull request merged**
