### PR TITLE
#1314 Correct traces in static compilation

### PR DESCRIPTION
**Pull request by lecourtoisflo**
Crash at destruction in static compilation

### CODE REVIEW

**Review by rosiereflo — APPROVED** [review]
by curiosity: why is this creating an issue? It was deleted several times at the end ?

**Comment by lecourtoisflo** [comment]
> by curiosity: why is this creating an issue? It was deleted several times at the end ?

It is possible, I just discovered in debugger that the crash happens during its destruction so I backdashed this part and it started working

**Comment by rosiereflo** [comment]
don't we risk to have a similar issue with sinks_ then?

**Comment by lecourtoisflo** [comment]
> don't we risk to have a similar issue with sinks_ then?

Sinks are destroyed automattically while original are destroyed manually. So no

**Review by gautierbureau — APPROVED** [review]

**Pull request merged**
