### PR TITLE
#3441 tTrigger reset if u changes

### PR DESCRIPTION
**Pull request by ErwanGuichard49**
Ensures a steady initialization if u(t = 0) = true.

closes [#3441](https://github.com/dynawo/dynawo/issues/3441)

### CODE REVIEW

**Review by joyelfeghali — DISMISSED** [review]

**Comment by joyelfeghali** [comment]
Is there any impact on the simulation results of models that use this block?

**Comment by ErwanGuichard49** [comment]
> Is there any impact on the simulation results of models that use this block?

**Comment by ErwanGuichard49** [comment]
> Is there any impact on the simulation results of models that use this block?

The modification impacts a few test cases, please do not merge this PR.

**Comment by ErwanGuichard49** [comment]
With the updates of branch 796, this PR can now be merged.

**Review by joyelfeghali — APPROVED** [review]

**Pull request merged**
