### PR TITLE
#1503 Remove useless reference when passing fundamental types in func…

### PR DESCRIPTION
**Pull request by gautierbureau**
…tions.

### CODE REVIEW

**Comment by rosiereflo** [comment]
I would expect an update on private side regarding models API

**Comment by gautierbureau** [comment]
> I would expect an update on private side regarding models API

There is one just not pushed yet

**Comment by rosiereflo** [comment]
ok thanks

**Review by rosiereflo — APPROVED** [review]

**Comment by rosiereflo** [comment]
OK for this one but I propose to wait before merging it there are still many bug fix that needs to be ported back into 1.2.1 and that kind of dev has the potential to break the cherry pick

**Comment by gautierbureau** [comment]
> OK for this one but I propose to wait before merging it there are still many bug fix that needs to be ported back into 1.2.1 and that kind of dev has the potential to break the cherry pick

OK

**Comment by rosiereflo** [comment]
Could you please resolve the conflicts? 
I guess we can merge this MR now as there is no more expected PR for 1.2.1

**Comment by gautierbureau** [comment]
> Could you please resolve the conflicts?
> I guess we can merge this MR now as there is no more expected PR for 1.2.1

done

**Pull request merged**
