### PR TITLE
#2191 Have one switchOffSignal/running for each side of an HVDC

### PR DESCRIPTION
**Pull request by cossartque**
Associated MR are coming in dynawo-rte, dynawo-interface and dynaflow-launcher. They must all be merged together.

### CODE REVIEW

**Review by adriguir — APPROVED** [review]
It seems fine for me. I suppose there are some tests with disconnection of only one side somewhere.

**Comment by cossartque** [comment]
> It seems fine for me. I suppose there are some tests with disconnection of only one side somewhere.

Just to be clear. This PR allows to have two switchOffSignals to avoid connecting switchOffSignal 1 to node 1 and switchOffSignal2 (which is not designed to do this) to node 2, as it was done in dynawo-interface for HvdcPV2.
But the models are not changed, and when you disconnect one side of the model, both sides are in fact disconnected in the equations. We could, in another PR, change the models so that we can operate one side only.

**Comment by adriguir** [comment]
> > It seems fine for me. I suppose there are some tests with disconnection of only one side somewhere.
> 
> Just to be clear. This PR allows to have two switchOffSignals to avoid connecting switchOffSignal 1 to node 1 and switchOffSignal2 (which is not designed to do this) to node 2, as it was done in dynawo-interface for HvdcPV2. But the models are not changed, and when you disconnect one side of the model, both sides are in fact disconnected in the equations. We could, in another PR, change the models so that we can operate one side only.

Nice, thank you for the complementary comment

**Comment by cossartque** [comment]
> > > It seems fine for me. I suppose there are some tests with disconnection of only one side somewhere.
> > 
> > 
> > Just to be clear. This PR allows to have two switchOffSignals to avoid connecting switchOffSignal 1 to node 1 and switchOffSignal2 (which is not designed to do this) to node 2, as it was done in dynawo-interface for HvdcPV2. But the models are not changed, and when you disconnect one side of the model, both sides are in fact disconnected in the equations. We could, in another PR, change the models so that we can operate one side only.
> 
> Nice, thank you for the complementary comment

As I created another issue to do it later on another PR, is it ok to merge this one (there are also dynawo-rte, dynawo-interface and dynaflow-launcher related PR) ?

**Pull request merged**
