### PR TITLE
873 cleanup since no need of virtual functions

### PR DESCRIPTION
**Pull request by e2l-su**
Added a 'const' somewhere, will you see it ? No more virtual methods since we do not use it.

### CODE REVIEW

**Comment by e2l-su** [comment]
About the failing check from Travis:
1 - it's normal failing until we/I fix the unitary test for the class. That test tries to call functions that are not here anymore. Test must evolve.
2 - I must figure out how come I did see that while running 'version-validation'. The test is present in the dynawo suite...

**Comment by rosiereflo** [comment]
Please update the test so that unit test compiles. You didn't see it running version-validation as it does not run unit tests. The target "build-tests" should be used.

**Comment by rosiereflo** [comment]
ps: no need to rerun version-validation after updating the tests

**Comment by e2l-su** [comment]
Rewriting the test will take some time since tests are built upon Google-Test suite which I don't know yet.
What must be done is to create a test specially for TapChangers that are neither Phase nor Ratio ones. A TapChanger without sizeG() evalG() sizeZ() evalZ().
I start doing it, but I don't know how to proceed now; l will learn. I'm worrying about not blocking merges

**Comment by rosiereflo** [comment]
OK I will update the tests afterwards.

**Comment by e2l-su** [comment]
Thanks rosierflo, thx :)

**Pull request merged**
