### PR TITLE
#902 Update zip library interface

### PR DESCRIPTION
**Pull request by lecourtoisflo**
Previous modification broke compilation with other platforms

### CODE REVIEW

**Review by rosiereflo — APPROVED** [review]

**Comment by gautierbureau** [comment]
Not sure it the right correction

**Comment by gautierbureau** [comment]
And I think I already corrected the issue

**Comment by rosiereflo** [comment]
damn I merged too fast

**Comment by gautierbureau** [comment]
I am not completly sure either

**Comment by rosiereflo** [comment]
which other commit would fix it?

**Comment by gautierbureau** [comment]
https://github.com/dynawo/dynawo/commit/de78e24ae9b42e39949206fa1e9547773af4184a

**Pull request merged**
