### PR TITLE
#1027 Add parameters for time step increase minimal requirement

### PR DESCRIPTION
**Pull request by adriguir**

### CODE REVIEW

**Review by gautierbureau — COMMENTED** [review]
Do we have a par example that would use the complete list of available parameters ?

**Review by rosiereflo — APPROVED** [review]

**Comment by gautierbureau** [comment]
My remark was not taken into account

**Comment by rosiereflo** [comment]
whoops sorry.
Large french testcases are using all parameters except those new ones.

**Comment by adriguir** [comment]
Will try to do something for the parameters use, either having an example file somewhere or having a few more examples dedicated to this in the examples section. Could be discussed together.

**Pull request merged**
